// Nutrition database extracted from HTML calculator
export const NUTRITION_DATA = {
  corn: {
    nameUr: 'مکئی',
    nameEn: 'Corn',
    energyLevel: 'high',
    proteinLevel: 'low',
    cp: 8,
    me: 12,
    ndf: 10,
    adf: 4,
    fat: 4,
    ca: 0.03,
    p: 0.25,
    notesUr: 'کاربوہائیڈریٹ میں زیادہ، پروٹین کم',
    notesEn: 'High starch, low protein',
  },
  barley: {
    nameUr: 'جو',
    nameEn: 'Barley',
    energyLevel: 'med',
    proteinLevel: 'low',
    cp: 11,
    me: 11,
    ndf: 18,
    adf: 6,
    fat: 2,
    ca: 0.05,
    p: 0.38,
    notesUr: 'متوسط توانائی',
    notesEn: 'Moderate energy',
  },
  wheat_bran: {
    nameUr: 'چوکر',
    nameEn: 'Wheat Bran',
    energyLevel: 'med',
    proteinLevel: 'med',
    cp: 15,
    me: 9,
    ndf: 30,
    adf: 12,
    fat: 4,
    ca: 0.12,
    p: 1.2,
    notesUr: 'فاسفورس زیادہ',
    notesEn: 'High phosphorus',
  },
  millet: {
    nameUr: 'باجرہ',
    nameEn: 'Millet',
    energyLevel: 'med',
    proteinLevel: 'low',
    cp: 10,
    me: 11,
    ndf: 14,
    adf: 6,
    fat: 4,
    ca: 0.02,
    p: 0.3,
  },
  rice_polish: {
    nameUr: 'رائس پولش',
    nameEn: 'Rice Polish',
    energyLevel: 'high',
    proteinLevel: 'low',
    cp: 13,
    me: 12,
    ndf: 22,
    adf: 9,
    fat: 13,
    ca: 0.1,
    p: 1.5,
    notesUr: 'گرمیوں میں مائیکوٹاکسن کا خطرہ',
    notesEn: 'Mycotoxin risk in monsoon',
  },
  sbm: {
    nameUr: 'سویا کھل',
    nameEn: 'Soybean Meal',
    energyLevel: 'low',
    proteinLevel: 'high',
    cp: 46,
    me: 10,
    ndf: 12,
    adf: 9,
    fat: 1.5,
    ca: 0.3,
    p: 0.7,
  },
  csm: {
    nameUr: 'کپاس کھل',
    nameEn: 'Cottonseed Meal',
    energyLevel: 'low',
    proteinLevel: 'high',
    cp: 38,
    me: 9,
    ndf: 25,
    adf: 18,
    fat: 2,
    ca: 0.15,
    p: 1.2,
    notesUr: 'افلاٹوکسِن خطرہ (بارشوں میں)',
    notesEn: 'Aflatoxin caution (monsoon)',
  },
  sfm: {
    nameUr: 'سورج مکھی کھل',
    nameEn: 'Sunflower Meal',
    energyLevel: 'low',
    proteinLevel: 'med',
    cp: 32,
    me: 8,
    ndf: 30,
    adf: 22,
    fat: 1,
  },
  rsm: {
    nameUr: 'سرسوں کھل',
    nameEn: 'Rapeseed Meal',
    energyLevel: 'low',
    proteinLevel: 'med',
    cp: 35,
    me: 9,
    ndf: 25,
    adf: 18,
    fat: 3,
  },
  guar: {
    nameUr: 'گوار کھل',
    nameEn: 'Guar Meal',
    energyLevel: 'low',
    proteinLevel: 'high',
    cp: 48,
    me: 8,
    ndf: 28,
    adf: 20,
    fat: 6,
  },
  straw: {
    nameUr: 'بھوسہ',
    nameEn: 'Straw',
    energyLevel: 'low',
    proteinLevel: 'low',
    cp: 4,
    me: 5,
    ndf: 70,
    adf: 45,
    fat: 1,
  },
  hay: {
    nameUr: 'خشک گھاس',
    nameEn: 'Hay',
    energyLevel: 'low',
    proteinLevel: 'low',
    cp: 9,
    me: 7,
    ndf: 55,
    adf: 35,
    fat: 2,
  },
  silage: {
    nameUr: 'سائیلج',
    nameEn: 'Silage',
    energyLevel: 'med',
    proteinLevel: 'low',
    cp: 9,
    me: 8,
    ndf: 45,
    adf: 30,
    fat: 3,
  },
  bypassFat: {
    nameUr: 'بائی پاس فیٹ',
    nameEn: 'Bypass Fat',
    energyLevel: 'high',
    proteinLevel: 'low',
    cp: 0,
    me: 20,
    ndf: 0,
    adf: 0,
    fat: 99,
    notesUr: 'زیادہ مقدار سے احتیاط',
    notesEn: 'Use within limits',
  },
  molasses: {
    nameUr: 'مولاسس',
    nameEn: 'Molasses',
    energyLevel: 'high',
    proteinLevel: 'low',
    cp: 5,
    me: 12,
    ndf: 0,
    adf: 0,
    fat: 0.5,
    notesUr: 'چپکاؤ کم کرنے کو خشک اجزاء کے ساتھ ملائیں',
    notesEn: 'Mix with dry matter',
  },
};

export const INGREDIENT_CATEGORIES = {
  energy: {
    titleEn: 'Energy Sources',
    titleUr: 'توانائی کے ذرائع',
    min: 1,
    ingredients: ['corn', 'barley', 'millet', 'rice_polish'],
  },
  protein: {
    titleEn: 'Protein Sources',
    titleUr: 'پروٹین کے ذرائع',
    min: 1,
    ingredients: ['sbm', 'csm', 'guar', 'sfm', 'rsm'],
  },
  fiber: {
    titleEn: 'Fiber Sources',
    titleUr: 'فائبر کے ذرائع',
    min: 1,
    ingredients: ['straw', 'hay', 'silage', 'wheat_bran'],
  },
  fat: {
    titleEn: 'Fat & Supplements',
    titleUr: 'چکنائی اور سپلیمنٹس',
    min: 0,
    ingredients: ['bypassFat', 'molasses'],
  },
};

export const STAGES = {
  dairy_cow: {
    en: ['Early Lactation', 'Mid Lactation', 'Late Lactation', 'Dry Period'],
    ur: ['شروع کا دودھ', 'درمیانی دودھ', 'آخری دودھ', 'خشک دور'],
  },
  bull: {
    en: ['Growing (100-200kg)', 'Fattening (200-300kg)', 'Finishing (>300kg)'],
    ur: ['بڑھوتری (100-200 کلو)', 'موٹا کرنا (200-300 کلو)', 'تیاری (>300 کلو)'],
  },
  buffalo: {
    en: ['Early Lactation', 'Mid Lactation', 'Late Lactation', 'Dry'],
    ur: ['شروع کا دودھ', 'درمیانی دودھ', 'آخری دودھ', 'خشک'],
  },
  heifer: {
    en: ['Weaning', 'Yearling', 'Pregnant'],
    ur: ['دودھ چھڑائی', 'ایک سال', 'گابھن'],
  },
};

export const ANIMALS = [
  { id: 'dairy_cow', image: '/animals/dairy-cow.jpg', labelEn: 'Dairy Cow', labelUr: 'دودھ والی گائے' },
  { id: 'bull', image: '/animals/fattening-bull.jpg', labelEn: 'Fattening Bull', labelUr: 'موٹا کرنے والا بیل' },
  { id: 'buffalo', image: '/animals/dairy-cow.jpg', labelEn: 'Buffalo', labelUr: 'بھینس' },
  { id: 'heifer', image: '/animals/goat.jpg', labelEn: 'Heifer', labelUr: 'جوان گائے' },
];

export const REGIONS = [
  { id: 'punjab', labelEn: 'Punjab', labelUr: 'پنجاب' },
  { id: 'sindh', labelEn: 'Sindh', labelUr: 'سندھ' },
  { id: 'kpk', labelEn: 'KPK', labelUr: 'خیبر پختونخوا' },
  { id: 'balochistan', labelEn: 'Balochistan', labelUr: 'بلوچستان' },
];

export const STATUS_INDICATORS = [
  {
    type: 'success',
    icon: '✅',
    titleUr: 'پروٹین ٹھیک ہے',
    titleEn: 'Protein is OK',
    descUr: 'تبدیلی کی ضرورت نہیں',
    descEn: 'No changes needed',
  },
  {
    type: 'warning',
    icon: '⚠️',
    titleUr: 'فائبر تھوڑا کم ہے',
    titleEn: 'Fiber slightly low',
    descUr: 'بھوسہ/خشک گھاس شامل کریں',
    descEn: 'Add straw/hay',
  },
  {
    type: 'error',
    icon: '🛑',
    titleUr: 'کیلشیم کم ہے',
    titleEn: 'Calcium low',
    descUr: 'چونا پتھر ضروری ہے',
    descEn: 'Add limestone',
  },
];
