'use client';

import { calculateNutrients, type FormulaItem } from '@/lib/calculations';
import { getIngredient, getNutritionRange } from '@/lib/constants';

interface PrintableRecipeProps {
  language: 'en' | 'ur';
  animal: string;
  stage: string;
  animalId: string | null;
  stageIndex: number;
  formula: FormulaItem[];
}

/**
 * Print-only recipe sheet. Hidden in normal screen layout via the
 * `print:hidden` / `hidden print:block` Tailwind utilities + the
 * `.printable-recipe` class which globals.css elevates only on @media print.
 *
 * Designed to fit on a single A4 / Letter page. The farmer can hand this
 * to a feed mill, stick it on the feed-bin, or save the print as a PDF.
 */
export function PrintableRecipe({
  language,
  animal,
  stage,
  animalId,
  stageIndex,
  formula,
}: PrintableRecipeProps) {
  const n = calculateNutrients(formula);
  const ranges = getNutritionRange(animalId, stageIndex);
  const totalKg  = n.totalAsFed;
  const date = new Date().toLocaleDateString(language === 'en' ? 'en-GB' : 'ur-PK');

  const t = {
    title:       language === 'en' ? 'Concentrate Feed Recipe' : 'کانسنٹریٹ فارمولا',
    forAnimal:   language === 'en' ? 'For' : 'برائے',
    stage:       language === 'en' ? 'Stage' : 'مرحلہ',
    date:        language === 'en' ? 'Date' : 'تاریخ',
    ingredients: language === 'en' ? 'Ingredients' : 'اجزاء',
    ingredient:  language === 'en' ? 'Ingredient' : 'جزو',
    qty:         language === 'en' ? 'Quantity' : 'مقدار',
    rate:        language === 'en' ? 'Rs/kg' : 'فی کلو',
    cost:        language === 'en' ? 'Cost (Rs)' : 'لاگت (روپے)',
    totals:      language === 'en' ? 'Totals' : 'کل',
    totalKg:     language === 'en' ? 'Total weight' : 'کل وزن',
    totalCost:   language === 'en' ? 'Total cost' : 'کل لاگت',
    perKg:       language === 'en' ? 'Cost per kg' : 'لاگت فی کلو',
    nutrients:   language === 'en' ? 'Nutritional Profile (DM basis)' : 'غذائی تجزیہ (خشک مادہ پر)',
    target:      language === 'en' ? 'Target' : 'ہدف',
    achieved:    language === 'en' ? 'Achieved' : 'حاصل',
    instructions: language === 'en' ? 'How to Mix & Feed' : 'ملانے اور کھلانے کا طریقہ',
    step1:       language === 'en'
      ? '1. Weigh each ingredient separately as listed above.'
      : '1. ہر جزو کو اوپر کے مطابق علیحدہ تولیں۔',
    step2:       language === 'en'
      ? '2. Grind grains coarsely (not too fine — fine grinding causes acidosis).'
      : '2. دانے کو موٹا پیسیں (بہت باریک نہ کریں — باریک پیسنا تیزابیت کا سبب)۔',
    step3:       language === 'en'
      ? '3. Mix all ingredients thoroughly so the mineral & salt are evenly spread.'
      : '3. تمام اجزاء کو اچھی طرح ملائیں تاکہ معدنیات اور نمک یکساں طور پر تقسیم ہو۔',
    step4:       language === 'en'
      ? '4. Feed alongside fresh forage (berseem, alfalfa, fodder) and clean water.'
      : '4. تازہ چارے (برسیم، لوسرن، چارہ) اور صاف پانی کے ساتھ کھلائیں۔',
    step5:       language === 'en'
      ? '5. Split into 2-3 feedings per day to avoid digestive upset.'
      : '5. روزانہ 2-3 وقت میں تقسیم کریں تاکہ ہاضمہ متاثر نہ ہو۔',
    cp:          language === 'en' ? 'Crude Protein (CP)' : 'پروٹین',
    me:          language === 'en' ? 'Energy (ME)' : 'توانائی',
    tdn:         language === 'en' ? 'TDN' : 'TDN',
    ndf:         language === 'en' ? 'Fiber (NDF)' : 'فائبر',
    fat:         language === 'en' ? 'Fat' : 'چکنائی',
    ca:          language === 'en' ? 'Calcium' : 'کیلشیم',
    p:           language === 'en' ? 'Phosphorus' : 'فاسفورس',
    footer:      language === 'en'
      ? 'Generated by Farm Nutrition Calculator. Always provide fresh clean water (≈50 L/day for a dairy cow).'
      : 'فارم غذائیت کیلکولیٹر سے تیار۔ ہمیشہ صاف پانی فراہم کریں (دودھیل گائے کے لیے ~50 لیٹر/دن)۔',
  };

  // Convert kg → bori (50 kg) for buying convenience
  const formatBori = (kg: number) => {
    const bori = kg / 50;
    return bori >= 0.1 ? ` (~${bori.toFixed(2)} bori)` : '';
  };

  const nutrientRows = [
    { label: t.cp,  value: n.protein,    unit: '%',         range: ranges?.protein,    decimals: 1 },
    { label: t.me,  value: n.energy,     unit: ' Mcal/kg',  range: ranges?.energy,     decimals: 2 },
    { label: t.tdn, value: n.tdn,        unit: '%',         range: ranges?.tdn,        decimals: 1 },
    { label: t.ndf, value: n.fiber,      unit: '%',         range: ranges?.fiber,      decimals: 1 },
    { label: t.fat, value: n.fat,        unit: '%',         range: ranges?.fat,        decimals: 1 },
    { label: t.ca,  value: n.calcium,    unit: '%',         range: ranges?.calcium,    decimals: 2 },
    { label: t.p,   value: n.phosphorus, unit: '%',         range: ranges?.phosphorus, decimals: 2 },
  ];

  return (
    // .printable-recipe is the marker globals.css uses to flip print visibility
    <div className="printable-recipe hidden print:block">
      {/* Header */}
      <div className="border-b-2 border-emerald-700 pb-3 mb-4">
        <h1 className="text-2xl font-bold text-emerald-900">🌾 {t.title}</h1>
        <div className="grid grid-cols-3 gap-3 mt-2 text-sm">
          <div>
            <span className="font-bold">{t.forAnimal}: </span>
            {animal}
          </div>
          <div>
            <span className="font-bold">{t.stage}: </span>
            {stage}
          </div>
          <div className="text-right">
            <span className="font-bold">{t.date}: </span>
            {date}
          </div>
        </div>
      </div>

      {/* Ingredients table */}
      <h2 className="text-lg font-bold text-emerald-800 mb-2">📋 {t.ingredients}</h2>
      <table className="w-full text-sm border border-gray-400 mb-4" style={{ borderCollapse: 'collapse' }}>
        <thead className="bg-emerald-100">
          <tr>
            <th className="border border-gray-400 px-2 py-1.5 text-left">#</th>
            <th className="border border-gray-400 px-2 py-1.5 text-left">{t.ingredient}</th>
            <th className="border border-gray-400 px-2 py-1.5 text-right">{t.qty}</th>
            <th className="border border-gray-400 px-2 py-1.5 text-right">{t.rate}</th>
            <th className="border border-gray-400 px-2 py-1.5 text-right">{t.cost}</th>
          </tr>
        </thead>
        <tbody>
          {formula.filter((f) => f.kg > 0.001).map((item, idx) => {
            const data = getIngredient(item.key);
            const name = data?.[language === 'en' ? 'nameEn' : 'nameUr'] ?? item.name;
            const price = item.price ?? data?.price ?? 0;
            const lineCost = item.kg * price;
            return (
              <tr key={item.key}>
                <td className="border border-gray-400 px-2 py-1.5">{idx + 1}</td>
                <td className="border border-gray-400 px-2 py-1.5">
                  {data?.icon ?? '🌾'} {name}
                </td>
                <td className="border border-gray-400 px-2 py-1.5 text-right font-mono">
                  {item.kg.toFixed(2)} kg{formatBori(item.kg)}
                </td>
                <td className="border border-gray-400 px-2 py-1.5 text-right font-mono">
                  Rs {price.toFixed(0)}
                </td>
                <td className="border border-gray-400 px-2 py-1.5 text-right font-mono">
                  Rs {lineCost.toFixed(0)}
                </td>
              </tr>
            );
          })}
          <tr className="bg-emerald-50 font-bold">
            <td colSpan={2} className="border border-gray-400 px-2 py-1.5 text-right">
              {t.totals}:
            </td>
            <td className="border border-gray-400 px-2 py-1.5 text-right font-mono">
              {totalKg.toFixed(2)} kg
            </td>
            <td className="border border-gray-400 px-2 py-1.5 text-right font-mono">
              Rs {n.perKgPrice}/kg
            </td>
            <td className="border border-gray-400 px-2 py-1.5 text-right font-mono">
              Rs {n.cost.toLocaleString()}
            </td>
          </tr>
        </tbody>
      </table>

      {/* Nutrition vs targets */}
      <h2 className="text-lg font-bold text-emerald-800 mb-2">📊 {t.nutrients}</h2>
      <table className="w-full text-sm border border-gray-400 mb-4" style={{ borderCollapse: 'collapse' }}>
        <thead className="bg-emerald-100">
          <tr>
            <th className="border border-gray-400 px-2 py-1.5 text-left">{t.ingredient}</th>
            <th className="border border-gray-400 px-2 py-1.5 text-right">{t.achieved}</th>
            <th className="border border-gray-400 px-2 py-1.5 text-right">{t.target}</th>
            <th className="border border-gray-400 px-2 py-1.5 text-center">✓ / ✗</th>
          </tr>
        </thead>
        <tbody>
          {nutrientRows.map((row) => {
            const inRange = row.range
              ? row.value >= row.range.min && row.value <= row.range.max
              : null;
            return (
              <tr key={row.label}>
                <td className="border border-gray-400 px-2 py-1.5">{row.label}</td>
                <td className="border border-gray-400 px-2 py-1.5 text-right font-mono">
                  {row.value.toFixed(row.decimals)}{row.unit}
                </td>
                <td className="border border-gray-400 px-2 py-1.5 text-right font-mono">
                  {row.range ? `${row.range.min}–${row.range.max}${row.unit}` : '—'}
                </td>
                <td className="border border-gray-400 px-2 py-1.5 text-center">
                  {inRange === null ? '—' : inRange ? '✓' : '✗'}
                </td>
              </tr>
            );
          })}
        </tbody>
      </table>

      {/* How-to-mix instructions */}
      <h2 className="text-lg font-bold text-emerald-800 mb-2">🔧 {t.instructions}</h2>
      <ol className="list-none space-y-1 text-sm mb-4 ml-2">
        <li>{t.step1}</li>
        <li>{t.step2}</li>
        <li>{t.step3}</li>
        <li>{t.step4}</li>
        <li>{t.step5}</li>
      </ol>

      {/* Footer */}
      <div className="border-t border-gray-300 pt-2 mt-4 text-xs text-gray-600 text-center">
        {t.footer}
      </div>
    </div>
  );
}
